### ISSUE TITLE
Incorrect table alignment

### ISSUE THREAD

**Issue by shehan360** [ballerina-platform/ballerina-dev-tools#109]
![Screenshot from 2021-05-27 11-10-54](https://user-images.githubusercontent.com/33398983/119772055-3a972a80-bedc-11eb-994d-e83f1976db3f.png)

**Comment by keizer619** [comment]
This view completed revamped with Central revamp effort. 
Current Page : https://central.ballerina.io/ballerina/io/1.6.0

Hence i will be closing this issue please feel free to reopen if there are any concerns
