### ISSUE TITLE
Private types in lang packages are not documented.

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-dev-tools#111]
**Description:**
`lang.array` documentation refers to a type called `AnydataType` [1]. This is a type name and does not provide users with any information about this type. This type is used in `indexOf` and `lastIndexOf` methods. But when trying to get details about `AnydataType` documentation does not provide any information [2]. IMO we should list and link private types getting exposed in documentation as well. We can be explicit about types being private.

[1] [lang.array/1.1.0/functions#lastIndexOf](https://docs.central.ballerina.io/ballerina/lang.array/1.1.0/functions#lastIndexOf)
[2] [lang.array/1.1.0/types](https://docs.central.ballerina.io/ballerina/lang.array/1.1.0/types)

**Comment by rdhananjaya** [comment]
We at least need to show the type-definition of module private type like `AnydataType` so that user can figure out what this type is about.

**Comment by shehan360** [comment]
I will be able to add `AnydataType` to types in API Docs.

However, links to these types(defined with `@typeParam`) are broken due to this issue - https://github.com/ballerina-platform/ballerina-lang/issues/31063
