### ISSUE TITLE
Links to Record Definitions in API Docs does not Working

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-dev-tools#112]
There are `internal server error` or `unexpected error` thrown from the links to record types in several modules.

Seems like the doc generation is not working properly for these. Most of the records have included fields.

For example, the `graphql:ListenerConfiguration` record has included fields. In graphql:alpha8 the link [1] worked fine.
But in graphql:beta.1 the link[2] does not work, it does not show this has included fields. When I am writing this issue down I also observed that the link [2] sometimes shows `An unexpected error has occurred.` error too.

I suspect this might be related to generating docs for record types which has included fields. But not sure.

[1] https://docs.central.ballerina.io/ballerina/graphql/0.2.0-alpha8/records/ListenerConfiguration
[2] https://docs.central.ballerina.io/ballerina/graphql/0.2.0-beta.1/records/ListenerConfiguration

**Comment by shehan360** [comment]
Fixed this with (https://github.com/wso2-enterprise/ballerina-central/pull/425) but the changes are not yet in prod.

The fix can be verified in dev (https://docs.dev-central.ballerina.io/ballerina/graphql/0.2.0-beta.1/records/ListenerConfiguration)
