### ISSUE TITLE
Need to Fix the "TypeID" Function Link of the "lang.typedesc" Module

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-tools#113]
Need to fix the "TypeID" function link of the "lang.typedesc" module[1].

<img width="1440" alt="Screenshot 2021-06-10 at 21 37 14" src="https://user-images.githubusercontent.com/11707273/121559335-2141c280-ca34-11eb-9b7f-7db3a77ed919.png">

[1] https://docs.central.ballerina.io/ballerina/lang.typedesc/1.0.0

**Comment by shehan360** [comment]
This issue is fixed. Hence closing the issue.
