### ISSUE TITLE
Ballerinax module doc page lists the same modules repeatedly

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-dev-tools#123]
**Description:**
[Ballerinax module doc](https://docs.central.ballerina.io/ballerinax) is updating to every connector release. Instead of this, We need to list only the connectors under this ballerinax with the latest version like [distribution doc](https://docs.central.ballerina.io/).
<img width="272" alt="Screenshot 2021-06-25 at 11 16 28 AM" src="https://user-images.githubusercontent.com/12771261/123376105-8c000b80-d5a7-11eb-81cf-0f3902db03ba.png">

**Comment by shehan360** [comment]
This issue is fixed now. Hence closing the issue.
