### ISSUE TITLE
Improve publish workflow

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-dev-tools#21]
- [ ] Fix sync release branch to master step
- [ ] Fix bumping node modules version to next SNAPSHOT, https://github.com/ballerina-platform/ballerina-dev-tools/pull/20/files#diff-09411745cd86a2defd5e968dbf4c4ccf7f3196ef083e2199ec5d3430f68045c6R3

**Comment by shehan360** [comment]
Closing as this issue is fixed.
