### ISSUE TITLE
Enable tests for windows build

### ISSUE THREAD

**Issue by AzeemMuzammil** [ballerina-platform/ballerina-dev-tools#221]
**Description:**
Due to the fact of intermittent test failures on only Windows build, certain tests were disabled for windows. This task is to track and enable those tests back, when those issues are fixed.

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Closed as the above PR is not merged
