### ISSUE TITLE
Need Static HTML Pages for Indexing the Bio Search

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-tools#28]
Currently, the old API Docs are appearing in the search results for Swan Lake when searched using the Bio search. 

<img width="1039" alt="Screenshot 2020-12-12 at 11 51 36" src="https://user-images.githubusercontent.com/11707273/101976994-70b75980-3c70-11eb-8088-07af10637f2d.png">

We need to generate the static HTML pages of the new API Docs to index them to appear as search results in the Bio search.

**Comment by shehan360** [comment]
Currently docs are generated using SSR(Server Side Rendering) using NextJS. Hence HTML pages are generated.
