### ISSUE TITLE
Need a Method to Check for Broken Links in API Docs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-tools#29]
Since the new API Docs are in one single app, and we don't have HTML pages, we are unable to run link checkers on it to find broken links.

Therefore, we need to find a way to check and identify broken links in the new API Docs in Swan Lake.

**Comment by shehan360** [comment]
With SSR in api docs, the broken link checker can be run against the docs site. Hence closing the issue.
