### ISSUE TITLE
Need to Fix All the API Docs Links in BBE Comments

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-tools#33]
Currently, all the links that are linked to elements in API Docs from the BBE comments are broken as the URL got changed with the redesigning. For example, see [1].

Need to fix them by changing the URL.

<img width="990" alt="Screenshot 2020-12-12 at 12 19 37" src="https://user-images.githubusercontent.com/11707273/101977593-76af3980-3c74-11eb-8959-33ff965bd9fd.png">

[1] https://ballerina.io/swan-lake/learn/by-example/base-path-and-path.html

**Comment by shehan360** [comment]
This issue is fixed. Hence closing the issue.
