### ISSUE TITLE
Module Names Should be in All Lower Case Letters

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-tools#42]
The module names in breadcrumbs and in the left navigation menu should be in all lower case letters. Currently, they start with an uppercase letter. For example, [1].

[1] https://ballerina.io/swan-lake/learn/api-docs/ballerina/index.html#/http

**Comment by shehan360** [comment]
This issue was fixed in this PR: https://github.com/ballerina-platform/ballerina-dev-tools/pull/38
Hence closing the issue.
