### ISSUE TITLE
Incorrect formatting in API docs

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-tools#69]
Refer the below formatting issue in [1] 

<img width="852" alt="image" src="https://user-images.githubusercontent.com/16300038/109200273-695f1100-77c6-11eb-828c-992e5e87dd24.png">

[1] https://ballerina.io/learn/api-docs/ballerina/#/ballerina/auth/1.1.0-alpha4/auth/classes/ListenerLdapUserStoreBasicAuthProvider

**Comment by shehan360** [comment]
This issue is caused by: https://github.com/ballerina-platform/ballerina-lang/issues/28916

**Comment by shehan360** [comment]
Closing as the above issue is fixed.
