### ISSUE TITLE
Have a Link with the Ballerina Logo to Link to the Bio

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-tools#83]
It is better to have the Ballerina logo and provide a link to navigate to the B.io from the Home page of both docs.central similar to what we have now in B.io.

**Comment by keizer619** [comment]
This is now available in the top after central revamp effort
Hence i will be closing this issue
<img width="1728" alt="Screenshot 2024-07-24 at 00 11 39" src="https://github.com/user-attachments/assets/18c13542-8900-4c92-acd6-4762c3d6a067">
