### ISSUE TITLE
Invalid `keywords` section in central docs home page

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-tools#86]
The keywords section in [1] does not contain all the keywords and also the existing keywords [2] gives 500 error.

<img width="823" alt="image" src="https://user-images.githubusercontent.com/16300038/112747797-3b433b80-8fd5-11eb-9759-32d253ecb943.png">

[1] https://docs.central.ballerina.io/
[2] https://docs.central.ballerina.io/keywords/slalpha3/readonly

**Comment by shehan360** [comment]
This issue is fixed with this PR: https://github.com/ballerina-platform/ballerina-dev-tools/pull/90
Hence closing the issue.
