### ISSUE TITLE
Words surrounded by backticks are not properly highlighted

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-tools#97]
See [1] for example

[1] https://docs.central.ballerina.io/ballerina/lang.array/1.1.0

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/16300038/117010866-e056df80-ad0a-11eb-828c-cedb554f877d.png">

**Comment by shehan360** [comment]
This issue is fixed by: https://github.com/ballerina-platform/ballerina-dev-tools/pull/100

Hence closing the issue.
